### ISSUE TITLE
dns-ui with Active Directory authorization

### ISSUE THREAD

**Issue by ajoergensen** [operasoftware/dns-ui#101]
Hi,

I'm trying to get dns-ui up and running with authentication against a Active Directory. Apache LDAP authentication works but I cannot figure out how to configure config.ini

```
[Mon Oct 22 20:56:15.057928 2018] [proxy_fcgi:error] [pid 1337:tid 140015153653504] [client 172.17.0.1:57260] AH01071: Got error 'PHP message: 1540234575: UserNotFoundException: User does not exist in LDAP. in /app/dns-ui/model/user.php:177\nPHP message: 1540234575: Stack trace:\nPHP message: 1540234575: #0 /app/dns-ui/model/user.php(110): User->get_details_from_ldap()\nPHP message: 1540234575: #1 /app/dns-ui/model/userdirectory.php(98): User->get_details()\nPHP message: 1540234575: #2 /app/dns-ui/requesthandler.php(24): UserDirectory->get_user_by_uid('user@mydomain.do...')\nPHP message: 1540234575: #3 /app/dns-ui/public_html/init.php(18): require('/app/dns-ui/req...')\nPHP message: 1540234575: #4 {main}\n', referer: http://localhost/
```

What I've tried is

```
[ldap]
enabled = 1
; Address to connect to LDAP server
host = ldap://ldap.server:389
; Use StartTLS for connection security (recommended if using ldap:// instead of ldaps:// above)
starttls = 0
; LDAP subtree containing USER entries
dn_user = "ou=Accounts,ou=Other,dc=MYDOMAIN,dc=DOM"
; LDAP subtree containing GROUP entries
dn_group = "OU=Groups,OU=Other,dc=MYDOMAIN,dc=DOM"

; Leave bind_dn empty if binding is not required
bind_dn = binduser@mydomain.dom
bind_password = PASSWORD

; User attributes
user_id = sAMAccountName
user_name = cn
user_email = mail
```

**Comment by drcain1** [comment]
I had to set these for my AD integration.

; Attribute of group where members are stored
group_member = member
; User attribute to compare with
group_member_value = dn
