### ISSUE TITLE
unable to add record

### ISSUE THREAD

**Issue by systeembeheerder** [operasoftware/dns-ui#148]
Adding an A record gives a php error:

`[Wed Jun 26 13:49:23.656586 2019] [proxy_fcgi:error] [pid 221:tid 139938817304320] [client 87.xxx.xxx.2:54502] AH01071: Got error 'PHP message: 1561549763: Pest_ServerError: {"error": "Internal Server Error"} in /opt/dns-ui/Pest.php:334
PHP message: 1561549763: Stack trace:
PHP message: 1561549763: #0 /opt/dns-ui/Pest.php(268): Pest->checkLastResponseForError()
PHP message: 1561549763: #1 /opt/dns-ui/Pest.php(466): Pest->doRequest(Resource id #7)
PHP message: 1561549763: #2 /opt/dns-ui/PestJSON.php(73): Pest->patch('zones/company.n...', '{"rrsets":[{"na...', Array)
PHP message: 1561549763: #3 /opt/dns-ui/powerdns.php(50): PestJSON->patch('zones/company.n...', Object(stdClass), Array)
PHP message: 1561549763: #4 /opt/dns-ui/model/zone.php(180): PowerDNS->patch('zones/company.n...', Object(stdClass))
PHP message: 1561549763: #5 /opt/dns-ui/model/zone.php(692): Zone->commit_changes()
PHP message: 1561549763: #6 /opt/dns-ui/views/api.php(147): Zone->process_bulk_json_rrset_update(Object(stdClass))
PHP message: 1561549763: #7 /opt/dns-ui/views/api.php(63): API->update_zone_rrsets('company.net.')
PHP message: 1561549763: #8 /opt/dns-ui/views/api.php(106): API->options(Array, Array)
PHP message: 1561549763: #9 /opt/dns-ui/views/api.php(33): API->zone('company.net.')
PHP message: 1561549763: #10 /opt/dns-ui/requesthandler.php(63): require('/opt/dns-ui/vie...')`
`PHP message: 1561549763: #11 /opt/dns-ui/public_html/init.php(18): require('/opt/dns-ui/req...')`
`PHP message: 1561549763: #12 {main}\n', referer: https://dns.company.net/zones/company.net`

![Capture](https://user-images.githubusercontent.com/19684880/60178820-96eafe80-981c-11e9-8511-5572d6ec42b4.PNG)

Any thoughts?

**Comment by systeembeheerder** [comment]
adding `binlog_format=row` to mariadb fixed the issue. Relevant PDNS error 
`Jul  4 14:30:24 dns1 pdns_server[411]: Jul 04 14:30:24 Backend reported permanent error which prevented lookup (GSQLBackend lookup query:Could not execute mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?: Lost connection to MySQL server during query), aborting
`Jul  4 14:30:24 dns1 pdns_server[411]: Jul 04 14:30:24 Backend error (retry once): GSQLBackend lookup query:Could not execute mysql statement: SELECT content,ttl,prio,type,domain_id,disabled,name,auth FROM records WHERE disabled=0 and type=? and name=?: Lost connection to MySQL server during query`
