### ISSUE TITLE
autocreate_reverse_records does not work with powerdns > 4.4

### ISSUE THREAD

**Issue by aba-rechsteiner** [operasoftware/dns-ui#192]
as of PowerDNS version 4.4 the set-ptr feature is no longer supported and therefore the autocreate_reverse_records does not work.

https://github.com/PowerDNS/pdns/pull/9593/files#diff-7240b871c4a8ef68cfaf28739c49d762abb6613c13b176ab776256930f4705a1

**Comment by thomas-pike** [comment]
That's unfortunate :( I guess we either have to remove the functionality, or, preferably implement it ourselves.

**Comment by aba-rechsteiner** [comment]
yes I think this is a must have, because you always need a PTR for an A/AAAA record. It would be really cool if this would be implemented.

**Comment by XANi** [comment]
It actually works in funny way for us - for existing PTR domains it works, for nonexisting ones we get nondescriptive

![image](https://user-images.githubusercontent.com/147394/216595391-b05cf61f-2424-4e66-a59e-8f3a81484127.png)

and corresponding stack trace
```
2023/02/03 12:27:18 [error] 545#545: *2811 FastCGI sent in stderr: "
PHP message: 1675423638: BadData in /var/www/html/dns-ui-0.2.7/model/zone.php:727
PHP message: 1675423638: Stack trace:
PHP message: 1675423638: #0 /var/www/html/dns-ui-0.2.7/views/api.php(147): Zone->process_bulk_json_rrset_update()
PHP message: 1675423638: #1 /var/www/html/dns-ui-0.2.7/views/api.php(63): API->update_zone_rrsets()
PHP message: 1675423638: #2 /var/www/html/dns-ui-0.2.7/views/api.php(106): API->options()
PHP message: 1675423638: #3 /var/www/html/dns-ui-0.2.7/views/api.php(33): API->zone()
PHP message: 1675423638: #4 /var/www/html/dns-ui-0.2.7/requesthandler.php(62): require('/var/www/html/d...')
PHP message: 1675423638: #5 /var/www/html/dns-ui-0.2.3/public_html/init.php(18): require('/var/www/html/d...')
PHP message: 1675423638: #6 {main}" while reading response header from upstream, client: 127.0.0.1, server: _, request: "PATCH /api/v2/zones/example.com. HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "www.example.com", referrer: "https://www.example.com/zones/non.3dart.com?name=ttt"
```

We'd be entirely fine with PTR zones not being created automatically (more than fine; that's actual use case for us, we don't want to create PTR for random domains clients give us to manage and have to point to some external IP) , or records not being created if PTR doesn't exist, just don't block editing records

**Comment by maltris** [comment]
When using the approval-feature, this error wont be shown directly. Clicking the "approve" button will only direct to a new page stating "The zone update failed. The following error message was given: " without any error message given.

Disabling the "autocreate_reverse_records" setting prevents this from happening.
