### ISSUE TITLE
ErrorException: Undefined property: stdClass:: in /srv/dns-ui/templates/zone.php:334

### ISSUE THREAD

**Issue by hvisage** [operasoftware/dns-ui#211]
Good day, 
 Busy with installing/testing/etc. and imported a zone file, which has remove and additions, I accepted the changes and then it gives this every time I try to access the zone. The zone list shows the zone have pending updates, but every time I try to access, it fails with this error

```
PHP message: 1718885021: ErrorException: Undefined property: stdClass:: in /srv/dns-ui/templates/zone.php:334
 PHP message: 1718885021: Stack trace:
 PHP message: 1718885021: #0 /srv/dns-ui/templates/zone.php(334): exception_error_handler()
 PHP message: 1718885021: #1 /srv/dns-ui/pagesection.php(69): include('...')
 PHP message: 1718885021: #2 /srv/dns-ui/pagesection.php(57): PageSection->generate()
 PHP message: 1718885021: #3 /srv/dns-ui/templates/base.php(81): PageSection->get()
 PHP message: 1718885021: #4 /srv/dns-ui/pagesection.php(69): include('...')
 PHP message: 1718885021: #5 /srv/dns-ui/views/zone.php(357): PageSection->generate()
 PHP message: 1718885021: #6 /srv/dns-ui/requesthandler.php(64): require('...')
 PHP message: 1718885021: #7 /srv/dns-ui/public_html/init.php(18): require('...')
 PHP message: 1718885021: #8 {main} while reading response header from upstream, client: 10.32.66.11, server: dns-ui.example.com, request: GET /zones/qquark.in HTTP/1.1, upstream: fastcgi://unix:/run/php/php8.2-fpm.sock:
```

**Comment by hvisage** [comment]
see: https://github.com/operasoftware/dns-ui/pull/212

**Comment by thomas-pike** [comment]
Fix merged. Thanks for the patch!
