### ISSUE TITLE
Pest_NotFound: {"error":"Not Found"} in /home/dnsui/Pest.php:311

### ISSUE THREAD

**Issue by lpar** [operasoftware/dns-ui#76]
I can log in, but the zones page gives me an error saying "Oops! Something went wrong!".

The PHP-FPM error log says:

```
[21-May-2018 22:28:47 UTC] 1526941727: Pest_NotFound: {"error":"Not Found"} in /home/dnsui/Pest.php:311
[21-May-2018 22:28:47 UTC] 1526941727: Stack trace:
[21-May-2018 22:28:47 UTC] 1526941727: #0 /home/dnsui/Pest.php(268): Pest->checkLastResponseForError()
[21-May-2018 22:28:47 UTC] 1526941727: #1 /home/dnsui/Pest.php(154): Pest->doRequest(Resource id #23)
[21-May-2018 22:28:47 UTC] 1526941727: #2 /home/dnsui/powerdns.php(30): Pest->get('zones', Array, Array)
[21-May-2018 22:28:47 UTC] 1526941727: #3 /home/dnsui/model/zonedirectory.php(129): PowerDNS->get('zones')
[21-May-2018 22:28:47 UTC] 1526941727: #4 /home/dnsui/model/user.php(219): ZoneDirectory->list_zones()
[21-May-2018 22:28:47 UTC] 1526941727: #5 /home/dnsui/views/zones.php(18): User->list_accessible_zones()
[21-May-2018 22:28:47 UTC] 1526941727: #6 /home/dnsui/requesthandler.php(64): require('/home/dnsui/vie...')
[21-May-2018 22:28:47 UTC] 1526941727: #7 /home/dnsui/public_html/init.php(18): require('/home/dnsui/req...')
[21-May-2018 22:28:47 UTC] 1526941727: #8 {main}
```
The pdns API seems to be working:

```
curl -D - -H 'X-API-Key: apikeyhere' -X GET http://127.0.0.1:8081/servers/localhost/zones
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 2
Content-Type: application/json
Server: PowerDNS/3.4.11

[]
```
I haven't set up any zones yet, I was planning on using the UI for that, so `[]` seems correct. Any ideas?

**Comment by thomas-pike** [comment]
The master branch and version 0.2+ releases of DNS UI only work with PowerDNS 4, as the PowerDNS API was _significantly_ changed between versions 3 and 4.

Since you are using PowerDNS 3.4.11 you will need to be using [version 0.1.3](https://github.com/operasoftware/dns-ui/releases/tag/v0.1.3) of DNS UI (which is the last release that supported PowerDNS 3). The easiest way to switch DNS UI to a PowerDNS 3-compatible version if you've cloned it from git is to checkout the powerdns3 branch: `git checkout -b powerdns3 origin/powerdns3`

Also make sure that the `api_url`  is set to the correct value in the `config/config.ini` file (typically  `"http://127.0.0.1:8081/servers/localhost/"` for PowerDNS 3).

As is mentioned in the documentation, I am not doing any further work on the powerdns3 branch, so if you are able to upgrade to PowerDNS 4.04 or higher, I recommend doing that instead.

**Comment by lpar** [comment]
Oops! Sorry. Have upgraded to PowerDNS 4.x, everything works now.
