### ISSUE TITLE
Split Zone Exception

### ISSUE THREAD

**Issue by shthead** [operasoftware/dns-ui#78]
Hi,

I am on the master branch. I noticed if I request a split zone (in my case I am splitting the zone "168.192.in-addr.arpa" into smaller zones), I get an error from the web UI. When I check the web server logs I see the following messages:

```
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: exception 'ErrorException' with message 'Indirect modification of overloaded property Zone::$dnssec has no effect' in /home/dns-web/model/zonedirectory.php:49, referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: Stack trace:, referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: #0 /home/dns-web/model/zonedirectory.php(49): exception_error_handler(8, 'Indirect modifi...', '/home/dns-web.d...', 49, Array), referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: #1 /home/dns-web/model/zonedirectory.php(108): ZoneDirectory->add_zone(Object(Zone)), referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: #2 /home/dns-web/views/zonesplit.php(72): ZoneDirectory->create_zone(Object(Zone)), referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: #3 /home/dns-web/requesthandler.php(64): require('/home/dns-web.d...'), referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: #4 /home/dns-web/public_html/init.php(18): require('/home/dns-web.d...'), referer: https://dns-web/zones/168.192.in-addr.arpa/split
[:error] [pid 2006] [client 192.168.34.231:12898] 1528867401: #5 {main}, referer: https://dns-web/zones/168.192.in-addr.arpa/split
```

**Comment by thomas-pike** [comment]
Thanks for the bug report. Looks like a regression caused by the adding of DNSSEC support. I'll see if I can reproduce the problem.
