### ISSUE TITLE
PHP Auth user does not exist.

### ISSUE THREAD

**Issue by 5hack** [operasoftware/dns-ui#79]
Hi, I'm having an issue with setting up DNS UI. Everything else should be okay. Just issue with auth, using basic Apache auth. 
Is this linked to something I need to configure in the [PHP_AUTH] section?  

Here is a printout of my Apache error log 
```
UserNotFoundException: User does not exist in PHP_AUTH variables. in /var/www/model/user.php:135
Stack trace:
#0 /var/www/model/user.php(112): User->get_details_from_php_auth()
#1 /var/www/model/userdirectory.php(98): User->get_details()
#2 /var/www/requesthandler.php(24): UserDirectory->get_user_by_uid('dns-user')
#3 /var/www/public_html/init.php(17): require('/var/www/dns-ui...')
#4 {main}
```

Vhost file
```
<VirtualHost *:80>
        ServerAdmin dns-user@localhost
        DocumentRoot /var/www/public_html/
        <Directory /var/www/public_html/>
        AuthType Basic
        AuthName "DNS UI"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
        AllowOverride none
        </Directory>
        DirectoryIndex init.php
        FallbackResource /init.php
        AllowEncodedSlashes NoDecode
</VirtualHost>
```
PS. Thanks for the awesome software. Looking forward to future updates and imporvements!

**Comment by thomas-pike** [comment]
Hi. The PHP_AUTH setup is only designed for use with a web server setup that is providing all user details (user ID, name and email) to the application via environment variables. If this is not the case you should disable this in the config. If you are trying to use DNS UI with just a local user database (no LDAP backend etc), know that support for this is not perfect and requires some extra manual setup work:

You will need to manually create the first user in the database via SQL command (this is something I hope to improve on soon). A query like the following should work: `insert into "user" (uid, name, email, admin) values ('dns-user', 'DNS User', 'dns-user@example.com', 1);` Any other needed users can then be created in the UI once you've managed to log into that first account.

**Comment by tabakhase** [comment]
Just ran into this - query above is missing the `active` flag.
```
psql -d dnsui -c 'update "user" set active=1'
```
fixes this.

---

Further `uid` has to match with the htpasswd username.
